#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : deprecated-Whoosh
Version  : 2.7.4
Release  : 26
URL      : http://pypi.debian.net/Whoosh/Whoosh-2.7.4.tar.gz
Source0  : http://pypi.debian.net/Whoosh/Whoosh-2.7.4.tar.gz
Summary  : Fast, pure-Python full text indexing, search, and spell checking library.
Group    : Development/Tools
License  : BSD-2-Clause
Requires: deprecated-Whoosh-license = %{version}-%{release}
Requires: deprecated-Whoosh-python = %{version}-%{release}
BuildRequires : buildreq-distutils
BuildRequires : buildreq-distutils3
BuildRequires : pytest
BuildRequires : setuptools_scm

%description
About Whoosh
============
Whoosh is a fast, featureful full-text indexing and searching library
implemented in pure Python. Programmers can use it to easily add search
functionality to their applications and websites. Every part of how Whoosh
works can be extended or replaced to meet your needs exactly.

%package legacypython
Summary: legacypython components for the deprecated-Whoosh package.
Group: Default
Requires: python-core

%description legacypython
legacypython components for the deprecated-Whoosh package.


%package license
Summary: license components for the deprecated-Whoosh package.
Group: Default

%description license
license components for the deprecated-Whoosh package.


%package python
Summary: python components for the deprecated-Whoosh package.
Group: Default
Provides: deprecated-whoosh-python

%description python
python components for the deprecated-Whoosh package.


%prep
%setup -q -n Whoosh-2.7.4

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1554303537
export MAKEFLAGS=%{?_smp_mflags}
python2 setup.py build -b py2

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/deprecated-Whoosh
cp LICENSE.txt %{buildroot}/usr/share/package-licenses/deprecated-Whoosh/LICENSE.txt
python2 -tt setup.py build -b py2 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files legacypython
%defattr(-,root,root,-)
/usr/lib/python2*/*

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/deprecated-Whoosh/LICENSE.txt

%files python
%defattr(-,root,root,-)
